name: "Smaple React CI Pipeline / Workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-letest

        steps:
            - name: 'Setup node JS'
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: 'Check node version'
              run: node --version
              